/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSubmitProtocolRouteImport } from './routes/api/public/submit-protocol'
import { Route as ApiPublicEcobagReserveRouteImport } from './routes/api/public/ecobag-reserve'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitProtocolRoute = ApiPublicSubmitProtocolRouteImport.update({
  id: '/api/public/submit-protocol',
  path: '/api/public/submit-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEcobagReserveRoute = ApiPublicEcobagReserveRouteImport.update({
  id: '/api/public/ecobag-reserve',
  path: '/api/public/ecobag-reserve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/ecobag-reserve': typeof ApiPublicEcobagReserveRoute
  '/api/public/submit-protocol': typeof ApiPublicSubmitProtocolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/ecobag-reserve': typeof ApiPublicEcobagReserveRoute
  '/api/public/submit-protocol': typeof ApiPublicSubmitProtocolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/ecobag-reserve': typeof ApiPublicEcobagReserveRoute
  '/api/public/submit-protocol': typeof ApiPublicSubmitProtocolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/ecobag-reserve'
    | '/api/public/submit-protocol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/ecobag-reserve'
    | '/api/public/submit-protocol'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/ecobag-reserve'
    | '/api/public/submit-protocol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiPublicEcobagReserveRoute: typeof ApiPublicEcobagReserveRoute
  ApiPublicSubmitProtocolRoute: typeof ApiPublicSubmitProtocolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-protocol': {
      id: '/api/public/submit-protocol'
      path: '/api/public/submit-protocol'
      fullPath: '/api/public/submit-protocol'
      preLoaderRoute: typeof ApiPublicSubmitProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ecobag-reserve': {
      id: '/api/public/ecobag-reserve'
      path: '/api/public/ecobag-reserve'
      fullPath: '/api/public/ecobag-reserve'
      preLoaderRoute: typeof ApiPublicEcobagReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiPublicEcobagReserveRoute: ApiPublicEcobagReserveRoute,
  ApiPublicSubmitProtocolRoute: ApiPublicSubmitProtocolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
